### ISSUE TITLE
[Panorama Partners] - Fixed deviation from mean outlier option

### ISSUE THREAD

**Issue by ankurjuneja** [LabKey/targetedms#853]
[Spec](https://docs.google.com/document/d/1vczRLCmMlG2WTCBlkPkmP5Xtw4sOw8rB51WCQFHjKV0/edit)

### Tasks 📍

- [x] Outlier setup - backend - calculate new outlier counts, send to the UI @ankurjuneja 
- [x] Outlier setup - UI changes - add new outlier in qc metric config page 
- [x] QC summary tooltip over replicate changes 
- [x] QC plot changes 
- [x] Automated test changes
- [x] Manual Testing @labkey-sweta 
- [x] Backport to 24.3
