### ISSUE TITLE
[Panorama Partners Development] Migrate targetedms inline event handlers

### ISSUE THREAD

**Issue by labkey-adam** [LabKey/targetedms#860]
**Tasks**
- [x] PlotTypeCheckCombo.js
- [x] protein.js
- [x] calibrationCurve.jsp  (2 onchange handlers)
- [x] chromatogramsForm.jsp  (4 onclick handlers)
- [x] figuresOfMerit.jsp  (1 onclick handler)
- [x] pharmacokinetics.jsp  (2 onclick handlers)
- [x] Test fixes
- [x] Merge
