### ISSUE TITLE
[Panorama] Display outliers in heatmaps

### ISSUE THREAD

**Issue by ankurjuneja** [LabKey/targetedms#916]
### Tasks
- [x] Create a new java action to return outlier counts by peptide 
- [x] Create an html page with date range selector and calling the above action to get the data
- [x] Create outlier heatmap table with values having color gradient
- [x] Create a new webpart for the UI
- [x] Pass the date range to the action and filter the data 
- [x] Persist and make date range filter in synch with qc plots dashboard 📌 
- [x] Display total number of replicates and total outliers
- [x] code review
- [x] Test plan @ankurjuneja 
- [x] Manual testing @labkey-sweta 
- [x] verify TC & merge
